#! /bin/bash

# web-dev
alias web-run='dc-run web '
alias web-bundle='web-run bundle '
alias web-rails='web-bundle exec rails '
alias web-rake='web-bundle exec rake '
alias web-rspec='web-bundle exec rspec '
alias web-hanami='web-bundle exec hanami '

# docker
alias dc='docker-compose '
alias dc-run='dc run --rm '
alias dps='docker ps --format "table {{.Names}}\\t{{.Image}}\\t{{.Status}}"'

# Detect which `ls` flavor is in use
if ls --color > /dev/null 2>&1; then # GNU `ls`
	colorflag="--color"
else # OS X `ls`
	colorflag="-G"
fi

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    if [[ -r ~/.dircolors ]]
    then
      eval "$(dircolors -b ~/.dircolors)"
    else
      eval "$(dircolors -b)"
    fi
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
# shellcheck disable=SC2139
alias ls="command ls ${colorflag}"
# shellcheck disable=SC2139
alias ll="ls -alF ${colorflag}"
# shellcheck disable=SC2139
alias la="ls -A ${colorflag}"
# shellcheck disable=SC2139
alias l="ls -CF ${colorflag}"
# shellcheck disable=SC2139
alias lsd="ls -lF ${colorflag} | grep --color=never '^d'"

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias -- -="cd -"

# Git aliases
alias g="git"
alias gs="g s" # ghostscript is usually not what I mean
alias gds="g ds"
alias gd="g d"
alias gco="g checkout"
alias gc=". /usr/local/bin/gitdate && git commit -v "

alias h="history"
alias dl="cd ~/Downloads"
alias path='echo $PATH | tr -s ":" "\n"'

if type nvim > /dev/null 2>&1; then
  alias vim="nvim"
fi
