#! /bin/bash

# https://github.com/jessfraz/dotfiles/blob/be955f16c44d2f7b3bb5d27e97ff6cfbf77a2946/.aliases
for opener in browser-exec xdg-open cmd.exe cygstart "start" open; do
  if command -v $opener >/dev/null 2>&1; then
    if [[ "$opener" == "cmd.exe" ]]; then
      # shellcheck disable=SC2139
      alias open="$opener /c start";
    else
      # shellcheck disable=SC2139
      alias open="$opener";
    fi
    break;
  fi
done

# Linux specific aliases, work on both MacOS and Linux.
pbcopy() {
  stdin=$(</dev/stdin);
  # shellcheck disable=SC2230
  pbcopy="$(which pbcopy)";
  if [[ -n "$pbcopy" ]]; then
    echo "$stdin" | "$pbcopy"
  else
    echo "$stdin" | xclip -selection clipboard
  fi
}

pbpaste() {
  # shellcheck disable=SC2230
  pbpaste="$(which pbpaste)";
  if [[ -n "$pbpaste" ]]; then
    "$pbpaste"
  else
    xclip -selection clipboard -o
  fi
}

# web-dev
alias web-run='dc-run web '
alias web-bundle='web-run bundle '
alias web-rails='web-bundle exec rails '
alias web-rake='web-bundle exec rake '
alias web-rspec='web-bundle exec rspec '
alias web-hanami='web-bundle exec hanami '

# docker
alias dc='docker-compose '
alias dc-run='dc run --rm '
alias dps='docker ps --format "table {{.Names}}\\t{{.Image}}\\t{{.Status}}"'

# Detect which `ls` flavor is in use
if ls --color > /dev/null 2>&1; then # GNU `ls`
  colorflag="--color"
else # OS X `ls`
  colorflag="-G"
fi

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    if [[ -r ~/.dircolors ]]
    then
      eval "$(dircolors -b ~/.dircolors)"
    else
      eval "$(dircolors -b)"
    fi
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
# shellcheck disable=SC2139
alias ls="command ls ${colorflag}"
# shellcheck disable=SC2139
alias ll="ls -alF ${colorflag}"
# shellcheck disable=SC2139
alias la="ls -A ${colorflag}"
# shellcheck disable=SC2139
alias l="ls -CF ${colorflag}"
# shellcheck disable=SC2139
alias lsd="ls -lF ${colorflag} | grep --color=never '^d'"

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias -- -="cd -"

# Git aliases
alias g="git"
alias gs="g s" # ghostscript is usually not what I mean
alias gds="g ds"
alias gd="g d"
alias gco="g checkout"
alias gc=". /usr/local/bin/gitdate && git commit -vs " # verbose sign

alias tar-gz="tar -xvzf"
alias tar-xz="tar -xvf" # or .tar
alias tar-bz2="tar -xjvf"
alias tar-xkcd="xdg-open https://xkcd.com/1168"

alias h="history"
alias dl="cd ~/Downloads"
alias path='echo $PATH | tr -s ":" "\n"'
alias dotfiles="cd ~/code/dotfiles && vim"

if type nvim > /dev/null 2>&1; then
  alias vim="nvim"
fi

alias rebash='source ${HOME}/.bashrc'

alias weather='curl wttr.in'
alias moon='curl wttr.in/Moon'

##### tips thanks to http://fauxzen.com/speedtest-from-the-cli/
alias sspeedtest='echo "scale=2; `curl  --progress-bar -w "%{speed_download}" http://cachefly.cachefly.net/10mb.test -o test.zip ` / 131072" | bc | xargs -I {} echo {}Mb\/s && rm -rf test.zip'
