#! /bin/bash

dclean() {
  docker rm "$(docker ps -aq 2>/dev/null)"
  docker rm -v "$(docker ps --filter status=exited -q 2>/dev/null)"
  docker rmi "$(docker images --filter dangling=true -q 2>/dev/null)"
}

dstop() {
  if [ $# -eq 0 ]; then
    docker stop "$(docker ps -q)"
  else
    docker stop "$@"
  fi
}

denv() {
  docker run --rm -it ubuntu bash
}

ngrok() {
  mapping=''
  args=''
  if [ "$(uname)" == 'Darwin' ]; then
    mapping='-p 4040:4040' # use host.docker.internal instead

    for var in "$@"
    do
        if [[ $var =~ ^[0-9]+$ ]];
        then
          args+="host.docker.internal:$var ";
        else
          args+="$var ";
        fi
    done

  else
    mapping='--network host'
  fi

  # shellcheck disable=SC2086
  # shellcheck disable=SC2068
  docker run -it --rm \
    $mapping \
    klotzandrew/ngrok \
    ngrok ${args[@]}
}

awscli_no_st() {
  docker run --rm \
    -v "$(pwd):/project" \
    -w "/project" \
    -e "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" \
    -e "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" \
    -e "AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}" \
    klotzandrew/awscli "$@"
}

aws() {
  local awsenv
  if [[ ! -z ${AWS_ACCESS_KEY_ID} ]]; then
    awsenv=" \
      -e "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" \
      -e "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" \
      -e "AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}" \
      -e "AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}" \
    "
  fi

  local awsprofile
  if [[ ! -z ${AWS_PROFILE} ]]; then
    awsprofile="-e "AWS_PROFILE=${AWS_PROFILE}""
  fi

  docker run --rm \
    --log-driver none \
    -v "${HOME}/.aws:/root/.aws" \
    -v "$(pwd):/project" \
    -w "/project" \
    $awsenv \
    $awsprofile \
    klotzandrew/awscli "$@"
}

packer() {
  docker run --rm -it \
    -v "$(pwd):/project" \
    -w "/project" \
    -e "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" \
    -e "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" \
    -e "AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}" \
    -e "AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}" \
    hashicorp/packer:light "$@"
}
