#! /bin/bash

dclean() {
  docker system prune
}

dstop() {
  if [ $# -eq 0 ]; then
    docker ps -a --format '{{.Names}}' | xargs  -n1 -I {} -P 8 sh -c 'docker stop {}'
  else
    docker stop "$@"
  fi
}

denv() {
  docker run --rm -it ubuntu bash
}
