#! /bin/bash

# Map caps lock to esc (linux only)
command -v setxkbmap >/dev/null 2>&1 && setxkbmap -option caps:escape

# Sync history across sessions
PROMPT_COMMAND="history -a; history -c; history -r${PROMPT_COMMAND:+$'\n'$PROMPT_COMMAND}"

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=
HISTFILESIZE=

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# fzf solarized dark
export FZF_DEFAULT_OPTS='
  --color dark,hl:33,hl+:37,fg+:235,bg+:136,fg+:254
  --color info:254,prompt:37,spinner:108,pointer:235,marker:235
'

export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_CTRL_T_OPTS="--preview '(highlight -O ansi -l {} 2> /dev/null || cat {} || tree -C {}) 2> /dev/null | head -200'"
export FZF_ALT_C_OPTS="--preview 'tree -C {} | head -200'"
# export FZF_DEFAULT_OPTS='--reverse --border --exact --height=50%'

# Use fd (https://github.com/sharkdp/fd) instead of the default find
_fzf_compgen_path() {
  fd --hidden --follow --exclude ".git" . "$1"
}

# Use fd to generate the list for directory completion
_fzf_compgen_dir() {
  fd --type d --hidden --follow --exclude ".git" . "$1"
}

editor=$(command -v nvim)
export EDITOR=$editor

# use a tty for gpg
# error: gpg failed to sign the data
GPG_TTY=$(tty)
export GPG_TTY

# mobile and optional
if [ "$(uname)" == 'Darwin' ]; then
  export ANDROID_HOME=${HOME}/Library/Android/sdk
  export ANDROID_SDK_ROOT=${ANDROID_HOME}
else
  export ANDROID_HOME=${HOME}/Android
  export ANDROID_SDK_ROOT=${ANDROID_HOME}/sdk
fi

# Clojure
java_dir=$(command -v java)
export JAVA_HOME="$java_dir"

# Node
export NVM_DIR="$HOME/.nvm"
# shellcheck source=/dev/null
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# shellcheck source=/dev/null
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"
# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

# Golang
export GOPATH="${HOME}/code/go"
export PATH=$PATH:/usr/local/go/bin
# shellcheck disable=SC2155
export PATH=$PATH:$(go env GOPATH)/bin

# Rust
export PATH="$HOME/.cargo/bin:$PATH"

# cuda for some gpu
export PATH="/usr/local/cuda-9.0/bin:$PATH"
export LD_LIBRARY_PATH="/usr/local/cuda-9.0/lib64:$LD_LIBRARY_PATH"

# Added by serverless binary installer
export PATH="$HOME/.serverless/bin:$PATH"

export CDPATH="${CDPATH}:${GOPATH}/src/github.com:${GOPATH}/src/golang.org:${GOPATH}/src"

# add Pulumi to the PATH
export PATH=$PATH:$HOME/.pulumi/bin

# shellcheck source=/dev/null
[ -s "$HOME/.config/envman/load.sh" ] && source "$HOME/.config/envman/load.sh"

# shellcheck source=/dev/null
[ -f "$HOME/.travis/travis.sh" ] && source "$HOME/.travis/travis.sh"

# fly.io
export FLYCTL_INSTALL="/home/klotz/.fly"
export PATH="$FLYCTL_INSTALL/bin:$PATH"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/home/klotz/.sdkman"
# shellcheck disable=SC1091
[[ -s "/home/klotz/.sdkman/bin/sdkman-init.sh" ]] && source "/home/klotz/.sdkman/bin/sdkman-init.sh"

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$HOME/.rvm/bin:$PATH"
