#! /bin/bash

# web-dev
alias web-run='dc-run web '
alias web-bundle='web-run bundle '
alias web-rails='web-bundle exec rails '
alias web-rake='web-bundle exec rake '
alias web-rspec='web-bundle exec rspec '
alias web-hanami='web-bundle exec hanami '

# docker
alias dc='docker-compose '
alias dc-run='dc run --rm '
alias dps='docker ps --format "table {{.Names}}\\t{{.Image}}\\t{{.Status}}"'

# Create a new directory and enter it
mkd() {
  mkdir -p "$@"
  cd "$@" || exit
}

# Make a temporary directory and enter it
tmpd() {
  local dir
  if [ $# -eq 0 ]; then
    dir=$(mktemp -d)
  else
    dir=$(mktemp -d -t "${1}.XXXXXXXXXX")
  fi
  cd "$dir" || exit
}
